//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Web08.Customize.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Web08.Customize.Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthSettings:Audience.
        /// </summary>
        public static string AuthSettings_Audience {
            get {
                return ResourceManager.GetString("AuthSettings_Audience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthSettings:Issuer.
        /// </summary>
        public static string AuthSettings_Issuer {
            get {
                return ResourceManager.GetString("AuthSettings_Issuer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthSettings:Key.
        /// </summary>
        public static string AuthSettings_Key {
            get {
                return ResourceManager.GetString("AuthSettings_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthSettings:RefreshTokenValidityInDays.
        /// </summary>
        public static string AuthSettings_RefreshTokenValidityInDays {
            get {
                return ResourceManager.GetString("AuthSettings_RefreshTokenValidityInDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthSettings:TokenValidityInMinutes.
        /// </summary>
        public static string AuthSettings_TokenValidityInMinutes {
            get {
                return ResourceManager.GetString("AuthSettings_TokenValidityInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete in database return 0.
        /// </summary>
        public static string DevMsg_DeleteEmployeesFailed {
            get {
                return ResourceManager.GetString("DevMsg_DeleteEmployeesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was not possible to connect the redis server(s).
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter employees in database return 0.
        /// </summary>
        public static string DevMsg_FilterEmployeeFailed {
            get {
                return ResourceManager.GetString("DevMsg_FilterEmployeeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get employee by ID in database return 0.
        /// </summary>
        public static string DevMsg_GetEmployeeByIDFailed {
            get {
                return ResourceManager.GetString("DevMsg_GetEmployeeByIDFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get from database return 0.
        /// </summary>
        public static string DevMsg_GetEmployeesFailed {
            get {
                return ResourceManager.GetString("DevMsg_GetEmployeesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert to database return 0.
        /// </summary>
        public static string DevMsg_InsertEmployeeFailed {
            get {
                return ResourceManager.GetString("DevMsg_InsertEmployeeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update in database return 0.
        /// </summary>
        public static string DevMsg_UpdateEmployeesFailed {
            get {
                return ResourceManager.GetString("DevMsg_UpdateEmployeesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp không được nhỏ hơn ngày sinh.
        /// </summary>
        public static string Employee_EmployeeCode_IdentityDateLessThanDOB {
            get {
                return ResourceManager.GetString("Employee_EmployeeCode_IdentityDateLessThanDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại.
        /// </summary>
        public static string Employee_EmployeeCode_NotDuplicate {
            get {
                return ResourceManager.GetString("Employee_EmployeeCode_NotDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to danh_sach_nhan_vien.
        /// </summary>
        public static string Excel_FileName {
            get {
                return ResourceManager.GetString("Excel_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH NHÂN VIÊN.
        /// </summary>
        public static string Excel_Title {
            get {
                return ResourceManager.GetString("Excel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/4.
        /// </summary>
        public static string MoreInfo_DeleteEmployeeFailed {
            get {
                return ResourceManager.GetString("MoreInfo_DeleteEmployeeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm hoặc cập nhật do trùng lặp thông tin.
        /// </summary>
        public static string MoreInfo_DuplicateEntry {
            get {
                return ResourceManager.GetString("MoreInfo_DuplicateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/4.
        /// </summary>
        public static string MoreInfo_Exception {
            get {
                return ResourceManager.GetString("MoreInfo_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/4.
        /// </summary>
        public static string MoreInfo_FilterEmployeeFailed {
            get {
                return ResourceManager.GetString("MoreInfo_FilterEmployeeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thêm hoặc cập nhật do ràng buộc khóa ngoại.
        /// </summary>
        public static string MoreInfo_ForeignKeyConstraint {
            get {
                return ResourceManager.GetString("MoreInfo_ForeignKeyConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/4.
        /// </summary>
        public static string MoreInfo_GetEmployeeByIDFailed {
            get {
                return ResourceManager.GetString("MoreInfo_GetEmployeeByIDFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/4.
        /// </summary>
        public static string MoreInfo_GetEmployeeFailed {
            get {
                return ResourceManager.GetString("MoreInfo_GetEmployeeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID truyền vào bị sai.
        /// </summary>
        public static string MoreInfo_IDNotMatch {
            get {
                return ResourceManager.GetString("MoreInfo_IDNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/4.
        /// </summary>
        public static string MoreInfo_InsertEmployeeFailed {
            get {
                return ResourceManager.GetString("MoreInfo_InsertEmployeeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com.vn/errorcode/4.
        /// </summary>
        public static string MoreInfo_UpdateEmployeeFailed {
            get {
                return ResourceManager.GetString("MoreInfo_UpdateEmployeeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra trong quá trình xác minh dữ liệu.
        /// </summary>
        public static string MoreInfo_ValidateError {
            get {
                return ResourceManager.GetString("MoreInfo_ValidateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_Delete.
        /// </summary>
        public static string Proc_Delete {
            get {
                return ResourceManager.GetString("Proc_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_Filter.
        /// </summary>
        public static string Proc_Filter {
            get {
                return ResourceManager.GetString("Proc_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetAll.
        /// </summary>
        public static string Proc_GetAll {
            get {
                return ResourceManager.GetString("Proc_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetByID.
        /// </summary>
        public static string Proc_GetByID {
            get {
                return ResourceManager.GetString("Proc_GetByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetByName.
        /// </summary>
        public static string Proc_GetByName {
            get {
                return ResourceManager.GetString("Proc_GetByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetNewCode.
        /// </summary>
        public static string Proc_GetNewCode {
            get {
                return ResourceManager.GetString("Proc_GetNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetUserByAccount.
        /// </summary>
        public static string Proc_GetUserByAccount {
            get {
                return ResourceManager.GetString("Proc_GetUserByAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetValidEmployeeCode.
        /// </summary>
        public static string Proc_GetValidEmployeeCode {
            get {
                return ResourceManager.GetString("Proc_GetValidEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_Insert.
        /// </summary>
        public static string Proc_Insert {
            get {
                return ResourceManager.GetString("Proc_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_Register.
        /// </summary>
        public static string Proc_Register {
            get {
                return ResourceManager.GetString("Proc_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_Update.
        /// </summary>
        public static string Proc_Update {
            get {
                return ResourceManager.GetString("Proc_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Role_Admin {
            get {
                return ResourceManager.GetString("Role_Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Role_User {
            get {
                return ResourceManager.GetString("Role_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá nhân viên thất bại.
        /// </summary>
        public static string UserMsg_DeleteEmployeeFailed {
            get {
                return ResourceManager.GetString("UserMsg_DeleteEmployeeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ðã có lỗi xảy ra! Vui lòng liên hệ MISA.
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lọc nhân viên thất bại.
        /// </summary>
        public static string UserMsg_FilterEmployeeFailed {
            get {
                return ResourceManager.GetString("UserMsg_FilterEmployeeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy nhân viên theo ID thất bại.
        /// </summary>
        public static string UserMsg_GetEmployeeByIDFailed {
            get {
                return ResourceManager.GetString("UserMsg_GetEmployeeByIDFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy danh sách nhân viên thất bại.
        /// </summary>
        public static string UserMsg_GetEmployeeFailed {
            get {
                return ResourceManager.GetString("UserMsg_GetEmployeeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới nhân viên thất bại.
        /// </summary>
        public static string UserMsg_InsertEmployeeFailed {
            get {
                return ResourceManager.GetString("UserMsg_InsertEmployeeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa nhân viên thất bại.
        /// </summary>
        public static string UserMsg_UpdateEmployeeFailed {
            get {
                return ResourceManager.GetString("UserMsg_UpdateEmployeeFailed", resourceCulture);
            }
        }
    }
}
